"""initial schema from current models

Revision ID: 6ed442800155
Revises: 
Create Date: 2026-04-07 13:57:53.867499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import polymarket_weather.db.models  # noqa: F401  - referenced by autogen op.create_table calls


# revision identifiers, used by Alembic.
revision: str = '6ed442800155'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icao_stations',
    sa.Column('station_id', sa.String(length=10), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('lon', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('elevation_m', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_report_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_index(op.f('ix_icao_stations_city_name'), 'icao_stations', ['city_name'], unique=False)
    op.create_table('risk_config',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_events',
    sa.Column('id', polymarket_weather.db.models._BigIntPK(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_severity_created', 'system_events', ['severity', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_table('system_state',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('city_icao_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_pattern', sa.String(length=100), nullable=False),
    sa.Column('station_id', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['icao_stations.station_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_icao_mapping_city_pattern'), 'city_icao_mapping', ['city_pattern'], unique=False)
    op.create_table('forecast_snapshots',
    sa.Column('id', polymarket_weather.db.models._BigIntPK(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=30), nullable=True),
    sa.Column('forecast_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['icao_stations.station_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_station_created', 'forecast_snapshots', ['station_id', 'created_at'], unique=False)
    op.create_table('metar_readings',
    sa.Column('id', polymarket_weather.db.models._BigIntPK(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('dewp', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('altim', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('wspd', sa.Integer(), nullable=True),
    sa.Column('wdir', sa.Integer(), nullable=True),
    sa.Column('wgst', sa.Integer(), nullable=True),
    sa.Column('visib', sa.String(length=10), nullable=True),
    sa.Column('cloud_cover', sa.JSON(), nullable=True),
    sa.Column('wx_string', sa.String(length=50), nullable=True),
    sa.Column('slp_hpa', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('metar_type', sa.String(length=10), nullable=True),
    sa.Column('temp_precise_c', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('raw_metar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['icao_stations.station_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'observed_at', name='uq_metar_station_obs')
    )
    op.create_index('ix_metar_station_observed', 'metar_readings', ['station_id', 'observed_at'], unique=False)
    op.create_table('poly_markets',
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('station_id', sa.String(length=10), nullable=True),
    sa.Column('metric', sa.String(length=20), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('threshold_upper', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=5), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('resolution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yes_token_id', sa.String(length=100), nullable=True),
    sa.Column('no_token_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_source', sa.Text(), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.String(length=100), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['icao_stations.station_id'], ),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_index('ix_poly_markets_active', 'poly_markets', ['status'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_poly_markets_city_name'), 'poly_markets', ['city_name'], unique=False)
    op.create_index(op.f('ix_poly_markets_event_id'), 'poly_markets', ['event_id'], unique=False)
    op.create_index(op.f('ix_poly_markets_resolution_at'), 'poly_markets', ['resolution_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', polymarket_weather.db.models._BigIntPK(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('our_p', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('market_p', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('edge', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('forecast_source', sa.String(length=30), nullable=False),
    sa.Column('forecast_snapshot', sa.JSON(), nullable=True),
    sa.Column('traded', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['poly_markets.market_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_detected_at'), 'opportunities', ['detected_at'], unique=False)
    op.create_index('ix_opportunities_market_detected', 'opportunities', ['market_id', 'detected_at'], unique=False)
    op.create_table('edge_calibration',
    sa.Column('id', polymarket_weather.db.models._BigIntPK(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', polymarket_weather.db.models._BigIntPK(), nullable=True),
    sa.Column('our_p', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('actual_outcome', sa.Boolean(), nullable=True),
    sa.Column('forecast_source', sa.String(length=30), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('station_id', sa.String(length=10), nullable=True),
    sa.Column('hours_to_resolution', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('edge_at_entry', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('calibrated_p', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calibration_source_resolved', 'edge_calibration', ['forecast_source', 'resolved_at'], unique=False)
    op.create_index(op.f('ix_edge_calibration_resolved_at'), 'edge_calibration', ['resolved_at'], unique=False)
    op.create_table('trades',
    sa.Column('id', polymarket_weather.db.models._BigIntPK(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', polymarket_weather.db.models._BigIntPK(), nullable=True),
    sa.Column('poly_order_id', sa.String(length=100), nullable=True),
    sa.Column('market_id', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.String(length=5), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('peak_pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('token_id', sa.String(length=100), nullable=True),
    sa.Column('size_usdc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fill_size_usdc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_result', sa.String(length=10), nullable=True),
    sa.Column('pnl_usdc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_market_id'), 'trades', ['market_id'], unique=False)
    op.create_index('ix_trades_market_status', 'trades', ['market_id', 'status'], unique=False)
    op.create_index(op.f('ix_trades_opportunity_id'), 'trades', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_trades_poly_order_id'), 'trades', ['poly_order_id'], unique=False)
    op.create_index('ix_trades_status_placed', 'trades', ['status', 'placed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_status_placed', table_name='trades')
    op.drop_index(op.f('ix_trades_poly_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_opportunity_id'), table_name='trades')
    op.drop_index('ix_trades_market_status', table_name='trades')
    op.drop_index(op.f('ix_trades_market_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_edge_calibration_resolved_at'), table_name='edge_calibration')
    op.drop_index('ix_calibration_source_resolved', table_name='edge_calibration')
    op.drop_table('edge_calibration')
    op.drop_index('ix_opportunities_market_detected', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_detected_at'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_poly_markets_resolution_at'), table_name='poly_markets')
    op.drop_index(op.f('ix_poly_markets_event_id'), table_name='poly_markets')
    op.drop_index(op.f('ix_poly_markets_city_name'), table_name='poly_markets')
    op.drop_index('ix_poly_markets_active', table_name='poly_markets', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('poly_markets')
    op.drop_index('ix_metar_station_observed', table_name='metar_readings')
    op.drop_table('metar_readings')
    op.drop_index('ix_forecast_station_created', table_name='forecast_snapshots')
    op.drop_table('forecast_snapshots')
    op.drop_index(op.f('ix_city_icao_mapping_city_pattern'), table_name='city_icao_mapping')
    op.drop_table('city_icao_mapping')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index('ix_events_severity_created', table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('risk_config')
    op.drop_index(op.f('ix_icao_stations_city_name'), table_name='icao_stations')
    op.drop_table('icao_stations')
    # ### end Alembic commands ###
